### ISSUE TITLE
Could provide a demo run step?

### ISSUE THREAD

**Issue by qpc001** [rmsander/lidar-lidar-cal#1]
Ohh, It is a fantastic work, But it is a little not friendly to a new man , could provide a demo run step?

**Comment by rmsander** [comment]
Hi @qpc001 !  Thank you for your kind comments and we appreciate you reaching out to us.  We have updated our `README` documentation to provide a more "step-by-step" recommended workflow through which you can use these calibration tools.  You can find this recommended workflow in our `README`, as well as here:

# Recommended Workflow 
Though we aim for these modules to be largely standalone and modular, we 
recommend the following workflow for pre-processing, estimating relative 
transformations, evaluating point cloud calibration quantity, and visualizing 
point clouds.  

**Note**: 
* **Steps 1-4** are for estimating the relative transformation between
lidar sensors, and performing internal evaluation of these transformations.  
* **Steps 5-6** are for analyzing and evaluating the quality 
of these transformations through perturbation analysis and lidar point cloud visualization.
* **Step 7** is for visualizing the estimated relative transformations between lidar
sensors using MATLAB.

**Steps**:

1. Convert the `rosbag` datasets into CSVs using the `rostopic echo` command below.
2. Run `calibration_optimization/clean_csvs.py` to pre-process the dataset and 
clean the column data.  See this file
below for instructions on how to run.  If you would like to examine the cross-correlation
of the odometry measurements over time, you can do so by running 
`calibration_optimization/timing_analysis.py`
3. Run `calibration_optimization/extract_yaml.py` to compute initial estimates for 
relative transformations between the lidar sensors on the Husky robots.  See this file
below for instructions on how to run.
4. Run `calibration_optimization/analysis.py`.  If you need to adjust the optimization or evaluation 
sub-routines, e.g. the cost function or weighting scheme, this can be done by modifying
the functions under `calibration_optimization/analysis_utils.py`.
5. To visualize the lidar scans (currently configured for running 3 rosbags at a time), you can do so 
by running our ROS launch file `lidar_pointcloud_anlaysis/runbags.launch`.
6. To run further analysis for evaluating point cloud consistency, you can 
run the following scripts (please make sure you are currently running the previous launch file), all under
`lidar_pointcloud_analysis/src/`.  See the specific notes for each of these files 
below under "Point Cloud Validation".
    * `analyze_perturbed.cpp`
    * `analyze_single.cpp`
    * `build_for_analysis.cpp`
    * `build_perturbed.cpp`
    * `ros_to_pcds.cpp`
    * `save_octomap.cpp`
    * `utils.cpp` 
7. To visualize the relative poses between the lidar sensors, you can do so using
`MATLAB_vis/drawtriad.m`.  Please check the `InitandFinalVizUNWEIGHTED.m` and 
`InitandFinalVizWEIGHTED.m` files to make sure the estimates match the transformations
being plotted.

Please reach out if you have any additional questions - thank you!
